const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const header=q('[data-header]'),toggle=q('[data-menu-toggle]'),menu=q('[data-menu]');
const setHeader=()=>header.classList.toggle('scrolled',scrollY>20);setHeader();addEventListener('scroll',setHeader,{passive:true});
toggle?.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});
menu?.addEventListener('click',e=>{if(e.target.closest('a')){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}});q('[data-year]').textContent=new Date().getFullYear();
const heroData={military:{icon:'⌁',title:'Logistics Specialist',copy:'Coordinated people, inventory, timelines, and high-stakes operations.',matches:[['Logistics Manager','Strong transfer','92%'],['Project Management Specialist','Adjacent direction','87%'],['Training & Development Manager','Emerging direction','81%']]},career:{icon:'↗',title:'Retail Operations Manager',copy:'Led teams, solved customer problems, analyzed performance, and improved processes.',matches:[['Customer Success Manager','Strong transfer','91%'],['Operations Analyst','Adjacent direction','86%'],['Training Manager','Emerging direction','82%']]},spouse:{icon:'◎',title:'Program Coordinator',copy:'Built adaptable experience across locations, roles, volunteer work, and family demands.',matches:[['Project Coordinator','Strong transfer','90%'],['Community Services Manager','Adjacent direction','84%'],['Human Resources Specialist','Emerging direction','79%']]}};
qa('[data-hero-role]').forEach(btn=>btn.addEventListener('click',()=>{qa('[data-hero-role]').forEach(b=>b.classList.toggle('active',b===btn));const d=heroData[btn.dataset.heroRole];q('[data-source-icon]').textContent=d.icon;q('[data-source-title]').textContent=d.title;q('[data-source-copy]').textContent=d.copy;['one','two','three'].forEach((n,i)=>{q(`[data-match-${n}]`).textContent=d.matches[i][0];q(`[data-match-${n}-note]`).textContent=d.matches[i][1];q(`[data-score-${n}]`).textContent=d.matches[i][2]})}));
let step=0;const tabs=qa('[data-step]'),panels=qa('[data-panel]'),dots=qa('.dots i'),prev=q('[data-prev]'),next=q('[data-next]'),labels=['Next: see directions','Next: compare fit','Next: see preparation','Next: build the plan','Restart the journey'];
function showStep(n){step=(n+5)%5;tabs.forEach((t,i)=>{const a=i===step;t.classList.toggle('active',a);t.setAttribute('aria-selected',String(a))});panels.forEach((p,i)=>p.classList.toggle('active',i===step));dots.forEach((d,i)=>d.classList.toggle('active',i===step));q('[data-progress-label]').textContent=`Step ${step+1} of 5`;prev.disabled=step===0;next.textContent=labels[step]}
tabs.forEach(t=>t.addEventListener('click',()=>showStep(Number(t.dataset.step))));prev.addEventListener('click',()=>showStep(step-1));next.addEventListener('click',()=>showStep(step===4?0:step+1));
const personas={adult:{quote:'“I know I’m capable of more. I need to see which parts of my experience transfer—and which paths are actually realistic.”',answer:'Translate years of experience into credible adjacent directions before starting another job search or training program.'},veteran:{quote:'“My military title does not explain everything I led, learned, and delivered. I need civilian options that recognize the full picture.”',answer:'Interpret military responsibilities and training in civilian career context without reducing a person to a title match.'},family:{quote:'“Every move reshapes both of our careers. We need a way to plan together without losing our individual goals.”',answer:'Support soldier-and-spouse planning in one environment while keeping each person’s experience and direction distinct.'}};
qa('[data-persona]').forEach(btn=>btn.addEventListener('click',()=>{qa('[data-persona]').forEach(b=>b.classList.toggle('active',b===btn));const d=personas[btn.dataset.persona];q('[data-persona-quote]').textContent=d.quote;q('[data-persona-answer]').textContent=d.answer}));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});qa('.reveal').forEach(el=>observer.observe(el));
